AWSTemplateFormatVersion: 2010-09-09
Resources:
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: terrafacer
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: TerraformBackends
  TerraformLockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: terraform
      Tags:
        - Key: Name
          Value: TerraformBackends
